Presentacion/Models/CursoViewModel.cs
using Datos.Entity;
using Negocio.Dto.Response;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Presentacion.Models {
    public class CursoViewModel {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Url { get; set; }
        public bool Publico { get; set; }
        public int Creditos { get; set; }
        public string Clave_Matriculacion { get; set; }
        public int Year_Diactado { get; set; }
        public string Tipo_Curso { get; set; }
        public string Dicta_Curso { get; set; }
        public string Informacion { get; set; }
        public DateTime Fecha_Limite_Inscripcion { get; set; }
        public int Nota_Minima_Aprobacion { get; set; }
        public int Nota_Maxima_Aprobacion { get; set; }
        public int? Nota_Minima_Examen { get; set; }
        public int? Nota_Maxima_Examen { get; set; }
        public int Comunicados { get; set; }
        public string Comunicado { get; set; }
        public string Titulo { get; set; }
        public string Texto { get; set; }
        public string Fecha_Publicacion { get; set; }

        public CursoViewModel() { }

        public List<Curso> LstCurso = new List<Curso>();
        public CursoViewModel(List<Curso> curso) {
            foreach (var c in curso) {
                LstCurso.Add(c);
            }
        }

        public List<ComunicadoResponse> LstComCur = new List<ComunicadoResponse>();
        public CursoViewModel(List<ComunicadoResponse> comfac) {
            foreach (var cf in comfac) {
                LstComCur.Add(cf);
            }
        }

        public List<ComunicadoCurso> LstComunicadoC = new List<ComunicadoCurso>();
        public CursoViewModel(List<ComunicadoCurso> comunicadoCurso) {
            foreach (var f in comunicadoCurso) {
                LstComunicadoC.Add(f);
            }
        }
    }
}

Presentacion/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Datos.Entity;
using Datos.Entity.GlobalesEntity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Negocio.Dto;
using Negocio.Dto.Response;
using Negocio.Services.Interfaces;
using Presentacion.Models;

namespace Presentacion.Controllers {
    public class CursoController : Controller {
        private readonly ICursoService cursoService;
        private readonly IMultyTenancyService multyTenancyService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IMultyTenancyService multyTenancy;
        CookieOptions option = new CookieOptions() { };
        public CursoController(IMultyTenancyService mt, ICursoService ics, IHttpContextAccessor httpContextAccessor) {
            cursoService = ics;
            multyTenancyService = mt;
            _httpContextAccessor = httpContextAccessor;
        }
       
        public IActionResult Add() {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CursoViewModel model) {
            if (ModelState.IsValid) {
                var cookieValue = Request.Cookies["UrlFacultad"];
                multyTenancyService.SeleccionarNodoFacultad(cookieValue);
                if (!cursoService.ValidateCurso(model.Nombre)) {
                    var c = new Curso() {
                        Nombre = model.Nombre,
                        Creditos = model.Creditos,
                        ClaveMatriculacion = model.Clave_Matriculacion,
                        YearDiactado = model.Year_Diactado,
                        TipoCurso = model.Tipo_Curso,
                        DictaCurso = model.Dicta_Curso,
                        Informacion = model.Informacion,
                        NotaMinimaAprobacion = model.Nota_Minima_Aprobacion,
                        NotaMaximaAprobacion = model.Nota_Maxima_Aprobacion,
                        NotaMinimaExamen = model.Nota_Minima_Examen,
                        NotaMaximaExamen = model.Nota_Maxima_Examen
                    };
                    cursoService.AddCurso(c);
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public IActionResult Edit(int id) {
            var curso = cursoService.get(id);
            var cursoModel = new CursoViewModel() {
                Id = id,
                Nombre = curso.Nombre,
                Creditos = curso.Creditos,
                Year_Diactado = curso.YearDiactado,
                Tipo_Curso = null,
                Dicta_Curso = null,
                Informacion = curso.Informacion,
                Nota_Minima_Aprobacion = curso.NotaMinimaAprobacion,
                Nota_Maxima_Aprobacion = curso.NotaMaximaAprobacion,
                Nota_Minima_Examen = curso.NotaMinimaExamen,
                Nota_Maxima_Examen = curso.NotaMaximaExamen
            };
            return View(cursoModel);
        }

        [HttpPost]
        public IActionResult Edit(CursoViewModel model) {
            var cookieValue = Request.Cookies["UrlFacultad"];
            multyTenancyService.SeleccionarNodoFacultad(cookieValue);
            var curso = cursoService.get(model.Id);
            curso.Nombre = model.Nombre;
            curso.Creditos = model.Creditos;
            curso.YearDiactado = model.Year_Diactado;
            curso.TipoCurso = null;
            curso.DictaCurso = null;
            curso.Informacion = model.Informacion;
            curso.NotaMinimaAprobacion = model.Nota_Minima_Aprobacion;
            curso.NotaMaximaAprobacion = model.Nota_Maxima_Aprobacion;
            curso.NotaMinimaExamen = model.Nota_Minima_Examen;
            curso.NotaMaximaExamen = model.Nota_Maxima_Examen;
            cursoService.ModifyCurso(curso);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id) {
            cursoService.DeleteCurso(id);
            return RedirectToAction("Index");
        }

        public IActionResult Index() {//El tenana ya se seleciono en el login
            var cookieValue = Request.Cookies["UrlFacultad"];
             multyTenancyService.SeleccionarNodoFacultad(cookieValue);
            var lstCurso=cursoService.ObtenerCursos();
            List<Curso> lst = new List<Curso>();
            foreach( var c in lstCurso) {
                var cvm = new Curso() {
                    Id = c.Id,
                    Nombre=c.Nombre,
                    Creditos = c.Creditos,
                };
                lst.Add(cvm);
            }
            var cursoVM = new CursoViewModel(lst);
            return View("Index", cursoVM);
        }

      public IActionResult ComunicadoCurso(int id) {
            Response.Cookies.Append("IdCurso", id.ToString(), option);
            return View();
        }

        [HttpPost]
        public IActionResult ComunicadoCurso(ComunicadosViewModel model) {
            multyTenancyService.SeleccionarNodoFacultad(Request.Cookies["UrlFacultad"]);
            var idCurso = Int16.Parse(Request.Cookies["IdCurso"]);
            var c = new Comunicado() {
                Id = model.Id,
                Titulo = model.Titulo,
                Texto = model.Texto,
                FechaPublicacion = model.Fecha_Publicacion,
            };
            cursoService.PublicarComunicadoCurso(idCurso, c.Titulo, c.Texto);
            return RedirectToAction("Index");
        }

        public ActionResult ListarComunicados(int idCurso) {
            multyTenancyService.SeleccionarNodoFacultad(Request.Cookies["UrlFacultad"]);
            var lista = cursoService.ListarComunicadoCurso(idCurso);
            var f = new CursoViewModel(lista);
            return View(f);
        }
    }
}

Presentacion/Views/Curso/Add.cshtml
@model Presentacion.Models.CursoViewModel
@Html.ActionLink("Menú principal", "MenuAdminFacu", "home")
    |
@Html.ActionLink("Docentes", "Index", "docente")
    |
@Html.ActionLink("Cursos", "Index", "curso")
<div style="padding:20px;"></div>
<legend>Crear un nuevo Curso</legend>
<center>
    @using (Html.BeginForm()) {
        <fieldset style="width:200px;">
            <div class="editor-label">
                @Html.LabelFor(model => model.Nombre)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Nombre)
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Creditos)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Creditos)
                @Html.ValidationMessageFor(model => model.Creditos, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Year_Diactado)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Year_Diactado)
                @Html.ValidationMessageFor(model => model.Year_Diactado, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Informacion)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Informacion)
                @Html.ValidationMessageFor(model => model.Informacion, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Nota_Minima_Aprobacion)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nota_Minima_Aprobacion)
                @Html.ValidationMessageFor(model => model.Nota_Minima_Aprobacion, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Nota_Maxima_Aprobacion)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nota_Maxima_Aprobacion)
                @Html.ValidationMessageFor(model => model.Nota_Maxima_Aprobacion, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Nota_Minima_Examen)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nota_Minima_Examen)
                @Html.ValidationMessageFor(model => model.Nota_Minima_Examen, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Nota_Maxima_Examen)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nota_Maxima_Examen)
                @Html.ValidationMessageFor(model => model.Nota_Maxima_Examen, "", new { @class = "custom_error" })
            </div>
            <br />
            <div class="buttons">
                <div>
                    <input type="submit" value="Agregar" />
                </div>
            </div>

        </fieldset>
    }
</center>

Presentacion/Views/Curso/ComunicadoCurso.cshtml
@model Presentacion.Models.ComunicadosViewModel
@Html.ActionLink("Menú principal", "MenuAdminFacu", "home")
    |
@Html.ActionLink("Docentes", "Index", "docente")
    |
@Html.ActionLink("Cursos", "Index", "curso")
<div style="padding:20px;"></div>
<div style="padding:20px;"></div>
<legend>Crear un nuevo Comunicado</legend>
<center>
    @using (Html.BeginForm()) {
        <fieldset style="width:200px;">

            <div class="editor-label">
                @Html.LabelFor(model => model.Titulo)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Titulo)
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Texto)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Texto)
                @Html.ValidationMessageFor(model => model.Texto, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Fecha_Publicacion)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Fecha_Publicacion)
                @Html.ValidationMessageFor(model => model.Fecha_Publicacion, "", new { @class = "custom_error" })
            </div>
            <br />
            <div class="buttons">
                <br />
                <br />
                <input type="submit" value="Agregar" />
            </div>
        </fieldset>
    }
</center>

Presentacion/Views/Curso/Edit.cshtml
@model Presentacion.Models.CursoViewModel
@Html.ActionLink("Menú principal", "MenuAdminFacu", "home")
    |
@Html.ActionLink("Docentes", "Index", "docente")
    |
@Html.ActionLink("Cursos", "Index", "curso")
<div style="padding:20px;"></div>
<legend>Editar Curso</legend>
<center>
    @using (Html.BeginForm()) {
        <fieldset style="width:200px;">
            <div style="padding:20px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Nombre)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nombre)
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Creditos)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Creditos)
                @Html.ValidationMessageFor(model => model.Creditos, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Year_Diactado)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Year_Diactado)
                @Html.ValidationMessageFor(model => model.Year_Diactado, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Informacion)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Informacion)
                @Html.ValidationMessageFor(model => model.Informacion, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Nota_Minima_Aprobacion)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nota_Minima_Aprobacion)
                @Html.ValidationMessageFor(model => model.Nota_Minima_Aprobacion, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Nota_Maxima_Aprobacion)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nota_Maxima_Aprobacion)
                @Html.ValidationMessageFor(model => model.Nota_Maxima_Aprobacion, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Nota_Minima_Examen)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nota_Minima_Examen)
                @Html.ValidationMessageFor(model => model.Nota_Minima_Examen, "", new { @class = "custom_error" })
            </div>
            <div style="padding:5px;"></div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Nota_Maxima_Examen)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nota_Maxima_Examen)
                @Html.ValidationMessageFor(model => model.Nota_Maxima_Examen, "", new { @class = "custom_error" })
            </div>
            @Html.HiddenFor(model => model.Nombre)
            <div class="buttons">
                <br />
                <input type="submit" value="Editar" />
            </div>
        </fieldset>
    }
</center>

Presentacion/Views/Curso/Index.cshtml
@model Presentacion.Models.CursoViewModel
@Html.ActionLink("Menú principal", "MenuAdminFacu", "home")
    |
@Html.ActionLink("Docentes", "Index", "docente")
    |
@Html.ActionLink("Cursos", "Index", "curso")
<div style="padding:20px;"></div>
<legend>Cursos</legend>
<br />
@Html.ActionLink("Crear un curso", "Add", "Curso")
<center>
    @using (Html.BeginForm()) {
        <fieldset>
            <br />
            <br />
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>

                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Creditos)
                        </th>
                        <th scope="col">
                            Opciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.LstCurso) {
                        <tr>
                            <td>
                                @Html.DisplayFor(item1 => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(item1 => item.Creditos)
                            </td>
                            <td>
                                @Html.ActionLink("Editar", "edit", "curso", new { id = item.Id })
                                /
                                @Html.ActionLink("Eliminar", "delete", "curso", new { id = item.Id }, new { onclick = "return confirm('Are you sure you want to delete?')" })
                                /
                                @Html.ActionLink("Agregar comunicado", "comunicadoCurso", "curso", new { id = item.Id })
                                /
                                @Html.ActionLink("Ver comunicados", "listarComunicados", "curso", new { idCurso = item.Id })
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </fieldset>
    }
</center>

Presentacion/Views/Curso/ListarComunicados.cshtml
@model Presentacion.Models.CursoViewModel
@Html.ActionLink("Menú principal", "MenuAdminFacu", "home")
    |
@Html.ActionLink("Docentes", "Index", "docente")
    |
@Html.ActionLink("Cursos", "Index", "curso")
<div style="padding:20px;"></div>
<div style="padding:20px;"></div>
<legend>Comunicados</legend>
<br />
<center>
    @using (Html.BeginForm()) {
        <fieldset>

            <br />
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Titulo)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Texto)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Fecha_Publicacion)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.LstComunicadoC) {
                    <tr>
                        <td>
                            @Html.DisplayFor(item1 => item.Titulo)
                        </td>
                        <td>
                            @Html.DisplayFor(item1 => item.Texto)
                        </td>
                        <td>
                            @Html.DisplayFor(item1 => item.FechaPublicacion)
                        </td>
                
                    </tr>
                    }
                </tbody>
            </table>
        </fieldset>
    }
</center>