Presentacion/Models/PersonaViewModel.cs
using Datos.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Presentacion.Models {
    public class PersonaViewModel {
        public int Id { get; set; }
        public int Ci { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public virtual ICollection<Cuenta> Persona { get; set; }

        public PersonaViewModel() { }
        public List<Persona> LstPersona = new List<Persona>();
        public PersonaViewModel(List<Persona> Persona) {
            foreach (var d in Persona) {
                LstPersona.Add(d);
            }
        }
    }
}

Presentacion/Controllers/PersonaController.cs
using Datos.Entity;
using Microsoft.AspNetCore.Mvc;
using Negocio.Services.Interfaces;
using Presentacion.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Presentacion.Controllers {
    public class PersonaController : Controller {
        private readonly IPersonaService personaService;
        private readonly IMultyTenancyService multyTenancyService;

        public PersonaController(IMultyTenancyService mt, IPersonaService ips) {
            personaService = ips;
            multyTenancyService = mt;
        }

        public IActionResult Index() {
            var lista = personaService.ListarPersona();
            var user = new PersonaViewModel(lista);
            return View(user);
        }

        public IActionResult Add() {
            return View();
        }

        [HttpPost]
        public IActionResult Add(PersonaViewModel model) {
            if (ModelState.IsValid) {
                if (!personaService.ValidatePersona(model.Ci)) {
                    var c = new Persona() {
                        Ci = model.Ci,
                        Nombre = model.Nombre,
                        Apellido = model.Apellido,
                        Cuentas = model.Persona
                    };
                    personaService.AddPersona(c);
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public IActionResult Edit(int id) {
            var persona = personaService.get(id);
            var personaModel = new PersonaViewModel() {
                Nombre = persona.Nombre,
                Apellido = persona.Apellido,
            };
            return View(personaModel);
        }

        [HttpPost]
        public IActionResult Edit(PersonaViewModel model) {
            var persona = personaService.get(model.Id);
            persona.Nombre = model.Nombre;
            persona.Apellido = model.Apellido;
            personaService.ModifyPersona(persona);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id) {
            personaService.DeletePersona(id);
            return RedirectToAction("Index");
        }

    }
}

Presentacion/Views/Persona/Add.cshtml
@model Presentacion.Models.PersonaViewModel

<div style="padding:20px;"></div>
@using (Html.BeginForm()) {
<fieldset>
    <legend>Crear un nuevo Usuario</legend>
    <div class="editor-label">
        @Html.LabelFor(model => model.Ci)
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Ci)
        @Html.ValidationMessageFor(model => model.Ci, "", new { @class = "custom_error" })
    </div>
    <div style="padding:5px;"></div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Nombre)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Nombre)
        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "custom_error" })
    </div>
    <div style="padding:5px;"></div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Apellido)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Apellido)
        @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "custom_error" })
    </div>
    <br />
    <div class="buttons">
        <div class="btn-primary">
            <br />
            <input type="submit" value="Agregar" />
        </div>
    </div>
</fieldset>
}

Presentacion/Views/Persona/Edit.cshtml
@model Presentacion.Models.PersonaViewModel
<div style="padding:20px;"></div>
@using (Html.BeginForm()) {
    <fieldset>
        <legend>Editar Perfil del Usuario</legend>
        <div style="padding:5px;"></div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "custom_error" })
        </div>
        <div style="padding:5px;"></div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Apellido)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Apellido)
            @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "custom_error" })
        </div>
        @Html.HiddenFor(model => model.Ci)
        <div class="buttons">
            <br />
            <input type="submit" value="Editar" />
        </div>
    </fieldset>
}

Presentacion/Views/Persona/Index.cshtml
@model Presentacion.Models.PersonaViewModel
<div style="padding:20px;"></div>
@using (Html.BeginForm()) {
    <fieldset>
        <legend>Usuarios</legend>
        <br />
        @Html.ActionLink("Crear un nuevo usuario", "Add", "Persona")
        <br />
        <br />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Ci)
                    </th>

                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Nombre)
                    </th>

                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Apellido)
                    </th>
                    <th scope="col">
                        Opciones
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.LstPersona) {
                    <tr>
                        <td>
                            @Html.DisplayFor(item1 => item.Ci)
                        </td>
                        <td>
                            @Html.DisplayFor(item1 => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(item1 => item.Apellido)
                        </td>
                        <td>
                            @Html.ActionLink("Editar", "edit", "Persona", new { id = item.Id })
                            @Html.ActionLink("Eliminar", "delete", "Persona", new { id = item.Id }, new { onclick = "return confirm('Are you sure you want to delete?')" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </fieldset>
}